# Generated by Django 5.0 on 2025-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.PositiveIntegerField(unique=True)),
                ("amount", models.BigIntegerField(help_text="sats")),
                ("payment_hash", models.CharField(max_length=64)),
                ("paid", models.BooleanField(default=False)),
                ("contributor", models.CharField(blank=True, max_length=100)),
                ("lnurl", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
